	create table cliente (
		id_cliente INT PRIMARY KEY,
		nome VARCHAR(50),
		data_nasc DATE,
		endereco VARCHAR(23)
	);
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (1, 'Lionello Molohan', '1996-04-29', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (2, 'Jobi McVanamy', '1988-02-19', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (3, 'Bev Grabban', '1986-02-04', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (4, 'Si Diter', '1989-03-26', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (5, 'Laney Denty', '1987-03-09', 'Rua Almirante Gavião');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (6, 'Natal Ickovits', '1993-04-22', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (7, 'Fabe Ritzman', '1989-07-10', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (8, 'Meredeth Rawdall', '1993-03-01', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (9, 'Eudora Larmuth', '1982-12-12', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (10, 'Wallie Camellini', '2001-04-01', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (11, 'Salvatore Bamsey', '1998-10-10', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (12, 'Tome Puffett', '1990-11-09', 'Rua Abreu Vieira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (13, 'Allissa Goodread', '1990-06-03', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (14, 'Aubine Yerby', '1999-01-01', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (15, 'Ginger Mugridge', '1986-12-24', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (16, 'Chad Cresser', '1990-01-03', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (17, 'Florinda Ferrini', '1981-05-05', 'Rua Almirante Gavião');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (18, 'Orton Tighe', '1980-07-02', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (19, 'Jayson Marre', '2002-03-13', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (20, 'Aridatha Obeney', '1980-03-03', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (21, 'Nadia Egginson', '1999-12-13', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (22, 'Filippa Steenson', '1999-01-05', 'Rua Abreu Vieira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (23, 'Petronille Fannon', '1995-09-26', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (24, 'Guthry Munn', '1999-04-13', 'Rua Abreu Vieira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (25, 'Ody Van T''Hoog', '1988-01-15', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (26, 'Christophorus Bourtoumieux', '1983-12-26', 'Rua Almirante Gavião');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (27, 'Saundra Anthiftle', '1982-03-03', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (28, 'Oswell D''Ambrosio', '1986-06-20', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (29, 'Emmerich Grenshiels', '1995-02-11', 'Travessa Acis Castilho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (30, 'Adelina Courvert', '1981-06-13', 'Rua Aires Gomes');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (31, 'Frederich Headan', '1983-01-01', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (32, 'Pietra Sturror', '1984-09-04', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (33, 'Dal Howles', '1997-10-05', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (34, 'Kristel Judge', '1985-07-28', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (35, 'Dore Umbert', '1992-09-03', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (36, 'Melisent Rolls', '2001-08-07', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (37, 'Michael Colleck', '1992-03-30', 'Rua Almirante Gavião');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (38, 'Morgan Helliwell', '1983-03-19', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (39, 'Hugibert Memory', '2001-07-06', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (40, 'Moses Pablos', '1981-05-16', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (41, 'Martie Shelly', '1990-11-02', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (42, 'Paige Kless', '1990-01-07', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (43, 'Raychel Gidman', '1989-01-31', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (44, 'Lodovico Bruckstein', '1983-05-29', 'Rua Alfredo Pinto');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (45, 'Drucill Doggrell', '1995-06-16', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (46, 'Amy Beckhouse', '2002-05-09', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (47, 'Roi Hinrich', '1988-10-17', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (48, 'Cal Thundercliffe', '1993-07-01', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (49, 'Didi Pearle', '1985-06-27', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (50, 'Nicholas Hutchason', '1982-02-25', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (51, 'Pete Sheasby', '1983-06-27', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (52, 'Edwin Asser', '1985-02-08', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (53, 'Jacqueline Cow', '1983-02-14', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (54, 'Odele McClenaghan', '1982-09-18', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (55, 'Rivy Graeber', '1989-11-03', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (56, 'Jaimie Dennerley', '1980-01-25', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (57, 'Ive Braunle', '2000-03-29', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (58, 'Wood Jakolevitch', '1989-07-18', 'Rua Aires Gomes');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (59, 'Shanie Gringley', '1985-12-03', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (60, 'Nissy Dudding', '1987-10-28', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (61, 'Cecilio Stather', '1995-06-06', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (62, 'Jeannette Cromly', '1997-01-29', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (63, 'Lock Lockhart', '1998-05-30', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (64, 'Audre Burmingham', '1989-01-25', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (65, 'Randolf Bodd', '1984-07-14', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (66, 'Judith Works', '1981-07-19', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (67, 'Waylin Begley', '1998-04-21', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (68, 'Guenna Poluzzi', '1988-02-22', 'Rua Aires Gomes');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (69, 'Bess Pyett', '1993-11-26', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (70, 'Kizzie Mattholie', '2001-02-13', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (71, 'Paolina Parcells', '1987-12-31', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (72, 'Aloysius Throssell', '1988-12-17', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (73, 'Vivie Semrad', '1990-08-30', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (74, 'Bambi Spurling', '1998-08-01', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (75, 'Elmo Prosser', '1999-11-15', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (76, 'Kermit Aukland', '1992-01-06', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (77, 'Rianon Korbmaker', '1988-07-02', 'Rua Almirante Gavião');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (78, 'Beatrisa Phippard', '1991-09-21', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (79, 'Reeta Robarts', '1980-03-28', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (80, 'Jesselyn Sijmons', '1995-12-25', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (81, 'Lorri Langshaw', '1986-05-31', 'Rua Aires Gomes');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (82, 'Harlie Bool', '1992-05-27', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (83, 'Nancey Tubridy', '1993-05-31', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (84, 'Jami Benedtti', '1985-08-26', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (85, 'Marwin Basson', '1993-01-01', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (86, 'Siegfried Moyne', '1988-06-30', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (87, 'Thorvald Marham', '1985-06-05', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (88, 'Al Domanek', '1990-10-24', 'Rua Alfredo Pinto');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (89, 'Verena Martschke', '1986-09-21', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (90, 'Finlay Ewells', '1986-10-17', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (91, 'Evie Scorton', '1995-01-04', 'Rua Almirante Gavião');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (92, 'Clerc Wanell', '1993-12-08', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (93, 'Lesli Raleston', '1994-10-04', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (94, 'Berkeley Pottinger', '1987-04-23', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (95, 'Katrine Laundon', '1994-01-30', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (96, 'Claribel Tousey', '1987-05-04', 'Rua Almirante Gavião');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (97, 'Temple McCurry', '1992-04-19', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (98, 'Ally Larraway', '1984-09-07', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (99, 'Cahra Buer', '1986-08-29', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (100, 'Ivonne Tanfield', '1989-01-23', 'Rua Almirante Cochrane');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (101, 'Base Rouge', '2000-07-21', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (102, 'Francesco Antecki', '1995-07-31', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (103, 'Hyatt Haill', '1999-09-18', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (104, 'Lindi Bartolomivis', '2002-06-10', 'Travessa Acis Castilho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (105, 'Vivian Diggar', '1982-03-11', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (106, 'Dov Alday', '1990-07-25', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (107, 'Abramo Di Lucia', '1995-05-24', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (108, 'Philip Ghelarducci', '1992-05-01', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (109, 'Nessie Basey', '1980-03-09', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (110, 'Brit Perry', '1983-07-14', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (111, 'Meier Filipowicz', '1982-07-04', 'Rua Alfredo Pinto');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (112, 'Jorey Blofield', '1992-09-03', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (113, 'Shandee Rayner', '1982-05-21', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (114, 'Caroline Stiger', '1995-02-21', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (115, 'Hilliary Fuster', '1984-12-20', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (116, 'Suzanna Snelling', '2002-03-11', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (117, 'Constanta Magnus', '1985-06-02', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (118, 'Carole Charette', '1998-07-07', 'Travessa Acis Castilho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (119, 'Joellyn Andrieu', '1982-06-24', 'Travessa Acis Castilho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (120, 'Levy Sidnell', '1990-04-07', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (121, 'Gris Skuse', '1984-07-19', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (122, 'Zeke McCathay', '1981-06-26', 'Rua Adolfo Mota');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (123, 'Annaliese Tuting', '1992-12-06', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (124, 'Saraann Larvor', '2002-12-07', 'Rua Alfredo Pinto');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (125, 'Gwyn Aspy', '1997-01-11', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (126, 'Giffer Bogie', '1997-05-05', 'Travessa Acis Castilho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (127, 'Jule Cianelli', '2001-12-07', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (128, 'Harriette Kettles', '1987-12-30', 'Rua Alves de Brito');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (129, 'Cynthy Syce', '1985-01-13', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (130, 'Yvonne Synnot', '2001-12-24', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (131, 'Leighton Castilla', '1980-11-17', 'Rua Alexandre de Gusmão');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (132, 'Deerdre Children', '1997-05-30', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (133, 'Barnabas Cockerill', '1987-01-29', 'Rua Alfredo Pinto');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (134, 'Audry Snookes', '1998-01-15', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (135, 'Chauncey Tardiff', '1992-12-08', 'Rua Abreu Vieira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (136, 'Clarice Barz', '2001-03-06', 'Rua Aires Gomes');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (137, 'Padraig Damerell', '1987-03-10', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (138, 'Faulkner MacArd', '1982-09-03', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (139, 'Manfred Valintine', '1998-05-15', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (140, 'Demetris Juarez', '1981-03-19', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (141, 'Edythe Garrigan', '1993-02-14', 'Rua Alfredo Pinto');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (142, 'Jeramey Hablet', '1980-07-30', 'Rua Afonso Pena');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (143, 'Brewster Toxell', '1996-01-24', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (144, 'Brigitta Collin', '1982-01-15', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (145, 'Terri-jo Brislan', '1996-01-26', 'Rua Agostinho');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (146, 'Matias Dumingo', '1999-09-01', 'Rua Alberto de Sequeira');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (147, 'Illa Kyne', '1987-08-28', 'Rua Aguiar');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (148, 'Kiel Sivill', '1985-07-07', 'Rua Abreu Lacerda');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (149, 'Tally Kalinke', '1993-07-01', 'Travessa Alice Maia');
	insert into cliente (id_cliente, nome, data_nasc, endereco) values (150, 'Meredithe Temperton', '1992-11-24', 'Travessa Acis Castilho');
